services:
  app:
    build: .
    working_dir: /nakajimap
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_APIKEY=${VITE_APIKEY}
      - VITE_AUTHDOMAIN=${VITE_AUTHDOMAIN}
      - VITE_DATABASEURL=${VITE_DATABASEURL}
      - VITE_PROJECT_ID=${VITE_PROJECT_ID}
      - VITE_STORAGE_BUCKET=${VITE_STORAGE_BUCKET}
      - VITE_MESSAGING_SENDER_ID=${VITE_MESSAGING_SENDER_ID}
      - VITE_APP_ID=${VITE_APP_ID}
      - VITE_MEASUREMENT_ID=${VITE_MEASUREMENT_ID}
    volumes:
      - ./nakajimap:/nakajimap
      - /nakajimap/node_modules
    ports:
      - 3000:3000
    command: npm run dev
